
services:
  server:
    build:
      context: .
      target: prod
    ports:
      - 8000:8000
    environment:
      NODE_ENV: production
      PORT: 8000
      ACCESS_SECRET_KEY: SOME_STRONG_KEY
      REFRESH_SECRET_KEY: SOME_STRONG_KEY2
      DB_URL: mongodb://root:example@mongo:27017/divar?authSource=admin
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
